.TH ilomex 8 "2025-06-01"

.SH "NAME"
ilomex \- a simple metrics exporter for old SUN ILOMs

.SH "SYNOPSIS"
.nh
.na
.HP
.B ilomex
[\fB\-LSVcdfh\fR]
[\fB\-l\ \fIfile\fR]
[\fB\-n\ \fIlist\fR]
[\fB\-p\ \fIport\fR]
[\fB\-s\ \fIip\fR]
[\fB\-v\ DEBUG\fR|\fBINFO\fR|\fBWARN\fR|\fBERROR\fR|\fBFATAL\fR]
.ad
.hy

.SH "DESCRIPTION"
.B ilomex
is a \fBm\fRetrics \fBex\fRporter for data provided by the ILOM of
older Sun Microsystems servers, such as the X4600 (SP Firmware 3.0.3.31 and
possibly others). It is specifically designed to collect power usage and
power supply (PSU) information — data that is only accessible via its WebUI,
but not via IPMI, SNMP or other operating system utilities.
The collected data can be exposed via HTTP in Prometheus exposition format [1]
This allows metric collector and time series database tools like VictoriaMetrics
and Prometheus to gather these metrics (e.g.,
via \fBhttp://\fIhostname\fB:\fI9300\fB/metrics\fR). These databases can then
be utilized to further process, reuse, or visualize the metrics using tools such
as Grafana [2], Netdata [3], or Zabbix [4].

\fBilomex\fR is written in plain C (having KISS in mind)
and thus it is extremely lightweight, has beside libprom, libmicrohttp,
libcurl and OS standard libs libc no other dependencies, is more
or less a standalone tool. It just queries the power configuration page
of the ILOM web interface (\fB/iPages/i_powermgmt.asp\fR), extracts the
curent, permitted and available power and provides them as metric export.
This is needed, because power usage data are available neither via SNMP,
nor IPMI, nr any other documented API.

Running \fBilomex\fR with root privileges should be safe, however,
there is no need to do that, therefore running \fBilomex\fR as a normal,
unprivileged user should be preferred. Similar an ILOM account with \fBRole\fR
.nh
\fBRead\ Only\ (o)\fR
.hy
should be used to login and retrieve the required data (see option -i...).


\fBilomex\fR operates in 3 modes:

.RS 2
.IP \fBdefault\fR 2
Just collects all data as it would for a /metrics HTTP request, print
it to the standard output and exit.
.IP \fBforeground\fR
Start the internal HTTP server to answer HTTP requests, but stays
attached to the console/terminal (i.e. standard input, output and error).
Use option \fB-f\fR to request this mode.
.IP \fBdaemon\fR
Start the internal HTTP server (daemon) to answer HTTP requests in the
background (fork-exec model) in a new session, detach from the
console/terminal, attach standard input, output and error to /dev/null
and finally exit with exit code \fB0\fR, if the daemon is running as
desired. Remember, if you do not specify a logfile to use, all messages
emitted by the daemon get dropped.
Use option \fB-d\fR to request this mode.
.RE

\fBilomex\fR answers one HTTP request after another to have a
very small footprint wrt. the system and queried device. So it is
recommended to adjust your firewalls and/or HTTP proxies accordingly.
If you need SSL or authentication, use a HTTP proxy like nginx - remember:
\fBilomex\fR should be kept as small and simple as possible.

When \fBilomex\fR runs in \fBforeground\fR or \fBdaemon\fR mode, it also
returns by default the duration of the following data collect and format tasks:
.RS 2
.TP 2
.B default
HTTP related statistics.
.TP
.B process
\fBilomex\fR process related data.
.TP
.B node
Statistics obtained from the ILOM.
.TP
.B libprom
All tasks together, i.e. sum of the default, process, and node task.
.RE

Note: Currently, ILOM queries are executed sequentially. This has the
beneficial side effect of preventing an ILOM from being overwhelmed by
too many requests. However, when collecting data from multiple ILOMs,
a slow or unresponsive ILOM can significantly delay the overall response
of this agent. In such cases, it is recommended to run a
separate ilomex instance for each ILOM.

.SH "OPTIONS"
.P
The following options are supported:

.TP
.B \-L
.PD 0
.TP
.B \-\-no\-scrapetime
Disable the overall scrapetime metrics (libprom collector), i.e. the time
elapsed when scraping all the required data. One needs to also disable
collecting scrapetimes of all other collectors before this option
gets honored. This is very helpful when one tries to determine the stats query
interval to use.

.TP
.B \-S
.PD 0
.TP
.B \-\-no\-scrapetime\-all
Disable recording the scrapetime of each collector separately. There is
one collector named \fBdefault\fR, which collects HTTP request/response
statistics, the optional \fBprocess\fR collector, which records metrics
about the ilomex process itself, the \fBnode\fR collector, which queries
the ILOM for data, and finally the \fBlibprom\fR collector,
which just records the time it took to collect and prom-format the data
of all other collectors.

.TP
.B \-V
.PD 0
.TP
.B \-\-version
Print \fBilomex\fR version info and exit.

.TP
.B \-c
.PD 0
.TP
.B \-\-compact
Sending a HELP and TYPE comment alias description about a metric is
according to the Prometheus exposition format [1] optional. With this
option they will be ommitted in the HTTP response and thus it saves
bandwith and processing time.

.TP
.B \-d
.PD 0
.TP
.B \-\-daemon
Run \fBilomex\fR in \fBdaemon\fR mode.

.TP
.B \-f
.PD 0
.TP
.B \-\-foreground
Run \fBilomex\fR in \fBforeground\fR mode.

.TP
.B \-h
.PD 0
.TP
.B \-\-help
Print a short help summary to the standard output and exit.

.TP
.BI \-i " file"
.PD 0
.TP
.BI \-\-iloms= file
Use \fIfile\fR to configure the ILOM queries. The file gets parsed
line-by-line:

.RS
.IP - 2
Everything after a '#' (including the '#' itself) is ignored.

.IP -
Empty lines or lines containing only whitespace are ignored.

.IP -
All other lines must contain a "\fBkey\fR: \fBvalue\fR" pair.

.IP -
Whitespace before and after the key and value is stripped.

.IP -
Each key defines a specific setting/property, which remains in effect
until it is overridden by another line with the same key.
Each \fBhost\fR key defines a new ILOM target, inheriting the current
settings.
Recognized keys are:

.RS
.TP 4
.B proto
The protocol used to communicate with the ILOM. Supported values
are: \fBhttp\fR (the default), \fBhttps\fR, and \fBinsecure\fR.
The latter implies HTTPS, but without verifying the ILOM's certificate.
.TP 4
.B host
The IP address or hostname of the ILOM to query.
.TP 4
.B port
The port used to connect to the ILOM. The default is 0, which
means "auto" (80 for HTTP and 443 for HTTPS). Allowed range: 0–65535.
.TP 4
.B user
The account used to log in to the ILOM. It should be a non-privileged
account with read-only permissions.
.TP 4
.B pw
The password used for ILOM login.
.TP 4
.B timeout
Timeout in seconds (1–600, initial value: 10). If the ILOM does not
respond within the specified time, the request is terminated, no data
is returned, and data collection for the corresponding host is suspended
for the next 5 minutes.
.TP 4
.B verbose
If set to "true", "1", or "on", instructs liburl to print additional
transfer-related information to stderr.
.RE

.RE

.TP
.BI \-l " file"
.PD 0
.TP
.BI \-\-logfile= file
Log all messages to the given \fIfile\fR when the main process is running.

.TP
.BI \-n " list"
.PD 0
.TP
.BI \-\-no-metric= list
Skip all the metrics given in the comma separated \fIlist\fR of identifiers.
Currently supported are:

.RS 4

.TP 4
.B version
All \filomex_version\fR metrics (default collector).
.TP 4
.B node
All \fBilomex_node_*\fR metrics (node collector).
.TP 4
.B process
All \fBilomex_process_*\fR metrics (process collector).

.RE

.TP
.BI \-p " num"
.PD 0
.TP
.BI \-\-port= num
Bind to port \fInum\fR and listen there for HTTP requests. Note that a port
below 1024 usually requires additional privileges. Default: 9300

.TP
.BI \-s " IP"
.PD 0
.TP
.BI \-\-source= IP
Bind the HTTP server to the given \fIIP\fR address, only. Per default
it binds to 0.0.0.0, i.e. all IPs configured on this host/zone/container.
If you want to enable IPv6, just specify an IPv6 address here (\fB::\fR
is the same for IPv6 as 0.0.0.0 for IPv4).

.TP
.BI \-v " level"
.PD 0
.TP
.BI \-\-verbosity= level
Set the message verbosity to the given \fIlevel\fR. Accepted tokens are
\fBDEBUG\fR, \fBINFO\fR, \fBWARN\fR, \fBERROR\fR, \fBFATAL\fR and for
convenience \fB1\fR..\fB5\fR respectively.


.SH "EXIT STATUS"
.TP 4
.B 0
on success.
.TP
.B 1
if an unexpected error occurred during the start (other problem).
.TP
.B 96
if an invalid option or option value got passed (config problem).
.TP
.B 100
if the logfile is not writable or port access is not allowed (permission problem).

.SH "EXAMPLES"
.TP
config file:
.nf
user: monitor
pw: changeme
#verbose: false
host: foo-m
\ 
verbose: true
host: bar-m
.ni

.SH "ENVIRONMENT"

.TP 4
.B PROM_LOG_LEVEL
If no verbosity level got specified via option \fB-v\ \fI...\fR, this
environment variable gets checked for a verbosity value. If there is a
valid one, the verbosity level gets set accordingly, otherwise \fBINFO\fR
level will be used.

.SH "BUGS"
https://github.com/jelmd/ilomex is the official source code repository
for \fBilomex\fR.  If you need some new features, or metrics, or bug fixes,
please feel free to create an issue there using
https://github.com/jelmd/ilomex/issues .

.SH "AUTHORS"
Jens Elkner

.SH "SEE ALSO"
[1]\ https://prometheus.io/docs/instrumenting/exposition_formats/
.br
[2]\ https://grafana.com/
.br
[3]\ https://www.netdata.cloud/
.br
[4]\ https://www.zabbix.com/
.\" # vim: ts=4 sw=4 filetype=nroff
